# H-004 · Beta Feature Suite

Factor test for **H-004** (equities): whether beta-derived features (asymmetric betas, Blume adjustment, residual momentum, and Fama–French–style smart-beta loadings) carry cross-sectional predictive power for forward returns at Alphalens `periods=(1, 5, 21)` (primary narrative **5d**).

- **Idea** — Build eleven cross-sectional features from rolling SPY OLS and a 4-factor (Carhart-style) regression; screen a balanced window grid on research IS only.
- **Claim** — Asymmetric betas / residual momentum / smart-beta loadings improve next-week IC beyond raw market beta.
- **Why it might work** — High downside beta is under-compensated for crash risk (Ang, Chen & Xing 2006); residual momentum isolates stock-specific drift after stripping systematic factors (Blitz, Huij & Martens 2011).
- **Data** — Daily OHLCV long panel (`s1_factor_panel_train.parquet`) + SPY daily returns + **ETF Tier A** Carhart proxies via `fetch_ff_factors_daily` (SPY / IWM / IWD / IWF / MTUM / BIL). Same schema as Ken French (`mkt_rf, smb, hml, mom, rf`) so `benchmark='ff'` is unchanged.

## Learning note (why not Ken French ZIPs)

The Ken French Data Library is free and research-grade but **monthly-lagged**, **historically revised**, and therefore **not point-in-time** for live trading or train–serve parity. Training smart-* features on Dartmouth ZIPs and deploying on a different factor construction would be covariate shift.

- **Archived ZIP fetcher:** `02_research/notebooks/s1_equities/redundant/old_fama_french_fetcher.py`
- **Archived notebook (Ken French path):** `02_research/notebooks/s1_equities/redundant/old_H-004_beta.ipynb`
- **Active fetcher:** `data.ingestion.alternative_data.fama_french_fetcher` (ETF proxies)

**Transferable lesson:** freeze only features you can recompute on the decision clock.

## Features (11 families via 8 store callers)

| Store caller | Output column(s) | `normalize` |
|---|---|---|
| `add_beta(benchmark='spy')` | `beta_{W}` | True (CS pct-rank) |
| `add_beta(benchmark='ff')` | `smart_beta_smb/hml/mom_{W}` | True |
| `add_downside_beta` | `downside_beta_{W}` | True |
| `add_upside_beta` | `upside_beta_{W}` | True |
| `add_net_beta_spread` | `net_beta_spread_{W}` | True |
| `add_relative_downside_beta` | `rel_downside_beta_{W}` | True |
| `add_relative_upside_beta` | `rel_upside_beta_{W}` | True |
| `add_blume_beta` | `blume_beta_{W}` | **none** (never CS-ranked) |
| `add_residual_momentum(benchmark='spy')` | `residual_mom_{K}_{S}` | **none** (never CS-ranked) |
| `add_residual_momentum(benchmark='ff')` | `smart_residual_mom_{K}_{S}` | **none** (never CS-ranked) |

**Workspace pattern:** the first SPY / FF store call runs OLS once per window and caches `_ws_*` columns; later callers reuse them. This notebook drops workspace columns before saving / evaluating.

**Normalize policy:** use library defaults for callers that expose `normalize`. Blume beta and residual momentum have no `normalize` kwarg and are never CS-ranked.

## Beta feature parquet cache

| Path | Role |
|------|------|
| `01_data/data_files/s1_equities/s1_factor_panel_train.parquet` | Research IS OHLCV (cold path only) |
| `01_data/data_files/s1_equities/s1_h004_beta_panel.parquet` | **Notebook artifact** — cleaned IS + all H-004 factor columns (no `_ws_*`) |

**Load gate:** if `s1_h004_beta_panel.parquet` exists and `FORCE_REBUILD` is False → load it into `panel` and **skip** §2 cleaning and §3 OLS rebuild.

**Save gate:** on a cold build, after features are built and workspace columns dropped, write the beta parquet **before** any Alphalens screen / tear sheet.

**Invalidate** by deleting the beta parquet or setting `FORCE_REBUILD = True` when changing `WINDOWS` / `FORMATION_WINDOWS` / `SKIPS`, after store-code changes, **or after switching factor backend (Ken French → ETF)** — smart_* columns change meaning.

This beta parquet is **not** a substitute for the train panel in other notebooks and must **not** be used for OOS / `feature_spec` freeze beyond this H-004 screen.

## Research IS discipline

- Cold path loads **`s1_factor_panel_train.parquet` only** — do not re-split.
- Do **not** use `s1_factor_panel_full.parquet` for window keep/kill.
- Overlapping 5d / 21d labels warrant purge/embargo in later walk-forward; this notebook screens IC on research IS only.
- Variant count = number of H-004 factor columns screened (expected **92**).

Use `data.processing.s1_feature_store` callers — do not reimplement OLS inline.

## 0. Imports & Config

Resolve the repo root; configure the balanced window grid, beta-cache paths, and Alphalens periods. Set `FORCE_REBUILD = True` to ignore an existing beta parquet and rebuild from the train IS (required once after the Ken French → ETF factor swap).

In [1]:
import os
import sys
import time

import alphalens as al
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.backends.backend_pdf import PdfPages

from data.ingestion.equity_fetcher import fetch_ohlcv
from data.ingestion.alternative_data.fama_french_fetcher import fetch_ff_factors_daily
from data.processing.cleaner import forward_fill_panel
from data.processing.feature_implementation.beta_features import market_return_frame
from data.processing.feature_implementation.beta_features import parse_beta_factor_name
from data.processing.s1_feature_store import (
    add_beta,
    add_blume_beta,
    add_downside_beta,
    add_net_beta_spread,
    add_relative_downside_beta,
    add_relative_upside_beta,
    add_residual_momentum,
    add_upside_beta,
    drop_beta_workspace,
)

# Jupyter cwd is often this notebook's folder, not the repo root; walk up until we find 01_data/ingestion.
ROOT = os.path.abspath(os.getcwd())
while not os.path.isdir(os.path.join(ROOT, "01_data", "ingestion")):
    parent = os.path.dirname(ROOT)
    if parent == ROOT:
        break
    ROOT = parent
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

TRAIN_PANEL_PATH = os.path.join(
    ROOT, "01_data", "data_files", "s1_equities", "s1_factor_panel_train.parquet"
)
BETA_PANEL_PATH = os.path.join(
    ROOT, "01_data", "data_files", "s1_equities", "s1_h004_beta_panel.parquet"
)
TEARSHEET_DIR = os.path.join(
    ROOT, "02_research", "notebooks", "s1_equities", "factor_tests", "tearsheets"
)

# --- Window screen (edit these lists) ---
WINDOWS = [42, 63, 84, 126, 189, 252]          # OLS / beta windows
FORMATION_WINDOWS = [84, 126, 189, 252]        # must be subset of WINDOWS
SKIPS = [10, 21, 42, 63]                        # residual-momentum skips (no extra OLS)

EXPECTED_N_FACTORS = (
    10 * len(WINDOWS) + 2 * len(FORMATION_WINDOWS) * len(SKIPS)
)  # 60 + 32 = 92

# --- Fixed for this notebook ---
FORCE_REBUILD = True   # True after Ken French -> ETF swap / window changes; then set False
BENCHMARK = "SPY"
PERIODS = (1, 5, 21)    # primary narrative = 5d
QUANTILES = 5
MAX_LOSS = 0.35

print(f"ROOT={ROOT}")
print(f"EXPECTED_N_FACTORS={EXPECTED_N_FACTORS}")
print(f"FORCE_REBUILD={FORCE_REBUILD}")

ROOT=c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio
EXPECTED_N_FACTORS=92
FORCE_REBUILD=True

## 1. Data Loading

### Beta parquet cache contract

1. If `FORCE_REBUILD` is False **and** `s1_h004_beta_panel.parquet` exists → **CACHE HIT**: load it into `panel` (features already present). Skip SPY / FF fetch (Alphalens prices use `panel["close"]`).
2. Otherwise → **CACHE MISS / cold build**: load `s1_factor_panel_train.parquet`, then fetch SPY and ETF Tier A Carhart proxies (`fetch_ff_factors_daily`) with a **40-day forward buffer** so Alphalens can form 21d forward returns near the last IS date.
3. On a warm load, validate H-004 column count via `parse_beta_factor_name`. If the cache looks stale (wrong count), fall through to a cold build.

Do **not** apply another 70/30 split here — the train parquet is already research IS.

In [2]:
use_beta_cache = (not FORCE_REBUILD) and os.path.exists(BETA_PANEL_PATH)
market_returns = None
ff_factors = None

if use_beta_cache:
    panel = pd.read_parquet(BETA_PANEL_PATH)
    panel["date"] = pd.to_datetime(panel["date"])
    FACTOR_COLS = [c for c in panel.columns if parse_beta_factor_name(c) is not None]
    if len(FACTOR_COLS) != EXPECTED_N_FACTORS:
        print(
            f"CACHE STALE: found {len(FACTOR_COLS)} H-004 cols "
            f"(expected {EXPECTED_N_FACTORS}) - falling back to cold build"
        )
        use_beta_cache = False
    else:
        print(f"CACHE HIT: loaded {BETA_PANEL_PATH}")
        n_tickers = panel["ticker"].nunique()
        n_dates = panel["date"].nunique()
        print(
            f"rows={len(panel):,}  tickers={n_tickers}  dates={n_dates:,}  "
            f"factor cols={len(FACTOR_COLS)}  "
            f"[{panel['date'].min().date()} -> {panel['date'].max().date()}]"
        )

if not use_beta_cache:
    panel = pd.read_parquet(TRAIN_PANEL_PATH)
    panel = panel.copy()
    panel["date"] = pd.to_datetime(panel["date"])
    required = {"date", "ticker", "close"}
    missing = required - set(panel.columns)
    if missing:
        raise ValueError(f"train panel missing columns: {sorted(missing)}")

    print(f"CACHE MISS: loaded {TRAIN_PANEL_PATH} (will build H-004 features)")
    n_tickers = panel["ticker"].nunique()
    n_dates = panel["date"].nunique()
    print(
        f"rows={len(panel):,}  tickers={n_tickers}  dates={n_dates:,}  "
        f"[{panel['date'].min().date()} -> {panel['date'].max().date()}]"
    )

    start = panel["date"].min().strftime("%Y-%m-%d")
    end = (panel["date"].max() + pd.Timedelta(days=40)).strftime("%Y-%m-%d")
    spy = fetch_ohlcv(BENCHMARK, start, end)
    market_returns = market_return_frame(spy)
    ff_factors = fetch_ff_factors_daily(start, end)
    print(f"SPY market returns: {len(market_returns):,} rows")
    print(f"FF factors: {len(ff_factors):,} rows  cols={list(ff_factors.columns)}")
    FACTOR_COLS = []

panel.head()

CACHE MISS: loaded c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\01_data\data_files\s1_equities\s1_factor_panel_train.parquet (will build H-004 features)
rows=289,287  tickers=100  dates=2,914  [2010-01-04 -> 2021-07-30]
SPY market returns: 2,941 rows
FF factors: 2,113 rows  cols=['date', 'mkt_rf', 'smb', 'hml', 'mom', 'rf']

        date ticker       open       high        low      close       volume
0 2010-01-04   AAPL   6.389116   6.421147   6.357684   6.406478  493729600.0
1 2010-01-04    ABT  17.989170  18.111998  17.899539  18.078800   10829095.0
2 2010-01-04   ADBE  36.650002  37.299999  36.650002  37.090000    4710200.0
3 2010-01-04    AET  29.090984  30.016525  28.918580  29.943932    5671979.0
4 2010-01-04    AIG  18.950967  18.957175  18.255746  18.553698    7750900.0

## 2. Data Cleaning & Engineering

**Cold path only:** forward-fill `close` (`limit=5`) then drop residual nulls.

**Warm path:** skip — the beta parquet already holds the cleaned panel + factors. No floor / winsorize in the store API.

In [3]:
if use_beta_cache:
    print("Skipping §2 - panel loaded from beta cache")
else:
    panel = forward_fill_panel(panel, columns=["close"], limit=5)
    panel = panel.dropna(subset=["close"]).reset_index(drop=True)
    print(
        f"after clean: rows={len(panel):,}  "
        f"null close={(panel['close'].isna().sum())}"
    )

after clean: rows=289,287  null close=0

## 3. Modeling / Signal Construction

### 3.1 H-004 beta feature suite

All SPY / FF callers share the same `WINDOWS` list so workspace OLS runs **once per window**. `FORMATION_WINDOWS` must be a subset of `WINDOWS`; `skip` only changes residual aggregation (no extra regression).

**Save gate (cold path):** after build + `drop_beta_workspace`, write `s1_h004_beta_panel.parquet` **before** Alphalens. Warm path skips the rebuild and re-derives `FACTOR_COLS` from the cached panel.

If runtime exceeds ~20 minutes on a cold run, trim `WINDOWS` in §0.

In [4]:
t0 = time.perf_counter()

if use_beta_cache:
    print("Skipping §3 rebuild - using cached H-004 columns")
    FACTOR_COLS = [c for c in panel.columns if parse_beta_factor_name(c) is not None]
else:
    # SPY family (7 single-window features)
    panel = add_beta(panel, market_returns, benchmark="spy", windows=WINDOWS)
    panel = add_downside_beta(panel, market_returns, windows=WINDOWS)
    panel = add_upside_beta(panel, market_returns, windows=WINDOWS)
    panel = add_net_beta_spread(panel, market_returns, windows=WINDOWS)
    panel = add_relative_downside_beta(panel, market_returns, windows=WINDOWS)
    panel = add_relative_upside_beta(panel, market_returns, windows=WINDOWS)
    panel = add_blume_beta(panel, market_returns, windows=WINDOWS)

    # FF family (3 smart betas)
    panel = add_beta(panel, ff_factors, benchmark="ff", windows=WINDOWS)

    # Residual momentum (CAPM + 4-factor)
    panel = add_residual_momentum(
        panel,
        market_returns,
        benchmark="spy",
        formation_window=FORMATION_WINDOWS,
        skip=SKIPS,
    )
    panel = add_residual_momentum(
        panel,
        ff_factors,
        benchmark="ff",
        formation_window=FORMATION_WINDOWS,
        skip=SKIPS,
    )

    panel = drop_beta_workspace(panel)
    FACTOR_COLS = [c for c in panel.columns if parse_beta_factor_name(c) is not None]
    assert len(FACTOR_COLS) == EXPECTED_N_FACTORS, (
        f"expected {EXPECTED_N_FACTORS} factor cols, got {len(FACTOR_COLS)}"
    )

    # Persist BEFORE Alphalens (cold path)
    os.makedirs(os.path.dirname(BETA_PANEL_PATH), exist_ok=True)
    panel.to_parquet(BETA_PANEL_PATH, index=False)
    print(f"Wrote beta feature panel -> {BETA_PANEL_PATH}")

elapsed = time.perf_counter() - t0
print(f"H-004 factor columns: {len(FACTOR_COLS)}  (build/load wall={elapsed:.1f}s)")
assert len(FACTOR_COLS) == EXPECTED_N_FACTORS, (
    f"expected {EXPECTED_N_FACTORS} factor cols, got {len(FACTOR_COLS)}"
)
assert not any(c.startswith("_ws_") for c in panel.columns), "_ws_* columns still present"
print("Factor columns:")
for c in sorted(FACTOR_COLS):
    print(f"  {c}")

Wrote beta feature panel -> c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\01_data\data_files\s1_equities\s1_h004_beta_panel.parquet
H-004 factor columns: 92  (build/load wall=623.7s)
Factor columns:
  beta_126
  beta_189
  beta_252
  beta_42
  beta_63
  beta_84
  blume_beta_126
  blume_beta_189
  blume_beta_252
  blume_beta_42
  blume_beta_63
  blume_beta_84
  downside_beta_126
  downside_beta_189
  downside_beta_252
  downside_beta_42
  downside_beta_63
  downside_beta_84
  net_beta_spread_126
  net_beta_spread_189
  net_beta_spread_252
  net_beta_spread_42
  net_beta_spread_63
  net_beta_spread_84
  rel_downside_beta_126
  rel_downside_beta_189
  rel_downside_beta_252
  rel_downside_beta_42
  rel_downside_beta_63
  rel_downside_beta_84
  rel_upside_beta_126
  rel_upside_beta_189
  rel_upside_beta_252
  rel_upside_beta_42
  rel_upside_beta_63
  rel_upside_beta_84
  residual_mom_126_10
  residual_mom_126_21
  residual_mom_126_42
  residual_mom_126_63
  residual_mom_189_10
  residual_mom_189_21
  residual_mom_189_42
  residual_mom_189_63
  residual_mom_252_10
  residual_mom_252_21
  residual_mom_252_42
  residual_mom_252_63
  residual_mom_84_10
  residual_mom_84_21
  residual_mom_84_42
  residual_mom_84_63
  smart_beta_hml_126
  smart_beta_hml_189
  smart_beta_hml_252
  smart_beta_hml_42
  smart_beta_hml_63
  smart_beta_hml_84
  smart_beta_mom_126
  smart_beta_mom_189
  smart_beta_mom_252
  smart_beta_mom_42
  smart_beta_mom_63
  smart_beta_mom_84
  smart_beta_smb_126
  smart_beta_smb_189
  smart_beta_smb_252
  smart_beta_smb_42
  smart_beta_smb_63
  smart_beta_smb_84
  smart_residual_mom_126_10
  smart_residual_mom_126_21
  smart_residual_mom_126_42
  smart_residual_mom_126_63
  smart_residual_mom_189_10
  smart_residual_mom_189_21
  smart_residual_mom_189_42
  smart_residual_mom_189_63
  smart_residual_mom_252_10
  smart_residual_mom_252_21
  smart_residual_mom_252_42
  smart_residual_mom_252_63
  smart_residual_mom_84_10
  smart_residual_mom_84_21
  smart_residual_mom_84_42
  smart_residual_mom_84_63
  upside_beta_126
  upside_beta_189
  upside_beta_252
  upside_beta_42
  upside_beta_63
  upside_beta_84

## 4. Evaluation

Alphalens runs only after `panel` is loaded from the beta parquet **or** freshly written to it — never mid-build.

Screen every H-004 column at `periods=(1, 5, 21)` with `quantiles=5`. Primary sort key: **`ic_5d`**. Decode column parameters with `parse_beta_factor_name`.

In [5]:
def to_alphalens_prices(panel: pd.DataFrame) -> pd.DataFrame:
    """Wide close matrix for Alphalens only (dates x tickers)."""
    prices = panel.pivot(index="date", columns="ticker", values="close")
    prices.index = pd.to_datetime(prices.index)
    return prices.sort_index()


def to_alphalens_factor(panel: pd.DataFrame, col: str) -> pd.Series:
    """MultiIndex (date, ticker) factor series for Alphalens."""
    factor = panel.set_index(["date", "ticker"])[col].dropna()
    factor.index = factor.index.set_levels(
        pd.to_datetime(factor.index.levels[0]), level=0
    )
    return factor.sort_index()


def _period_label(period_index: pd.Index, period: int, position: int):
    """Match Alphalens period label ('1D', '5D', ...) or fall back by position."""
    for c in (f"{period}D", f"{period}d", period, str(period)):
        if c in period_index:
            return c
    return period_index[position]


def factor_screen_metrics(
    factor: pd.Series,
    prices: pd.DataFrame,
    *,
    periods: tuple[int, ...] = PERIODS,
    quantiles: int = QUANTILES,
    max_loss: float = MAX_LOSS,
) -> dict:
    """Mean IC and Q5-Q1 mean return spread for each forward period."""
    factor_data = al.utils.get_clean_factor_and_forward_returns(
        factor=factor,
        prices=prices,
        quantiles=quantiles,
        periods=periods,
        max_loss=max_loss,
    )
    mean_ic = al.performance.mean_information_coefficient(factor_data)
    mean_ret, _ = al.performance.mean_return_by_quantile(factor_data, demeaned=True)

    row = {}
    for i, p in enumerate(periods):
        ic_key = _period_label(mean_ic.index, p, i)
        ret_key = _period_label(mean_ret.columns, p, i)
        row[f"ic_{p}d"] = float(mean_ic.loc[ic_key])
        q_hi, q_lo = mean_ret.index.max(), mean_ret.index.min()
        row[f"spread_{p}d"] = float(
            mean_ret.loc[q_hi, ret_key] - mean_ret.loc[q_lo, ret_key]
        )
    return row


def run_full_tear(
    panel: pd.DataFrame,
    factor_col: str,
    prices: pd.DataFrame,
    *,
    periods: tuple[int, ...] = PERIODS,
    quantiles: int = QUANTILES,
    max_loss: float = MAX_LOSS,
    tearsheet_dir: str = TEARSHEET_DIR,
):
    """Build factor_data, run Alphalens full tear, save figs to multi-page PDF.

    Alphalens calls plt.show() after each plot, which clears figures under Agg.
    Temporarily replace plt.show so each figure is written into the PDF before close.
    """
    if factor_col not in panel.columns:
        raise ValueError(
            f"{factor_col!r} not in panel - pick a screened column "
            f"(available: {FACTOR_COLS})"
        )
    plt.close("all")
    factor_data = al.utils.get_clean_factor_and_forward_returns(
        factor=to_alphalens_factor(panel, factor_col),
        prices=prices,
        quantiles=quantiles,
        periods=periods,
        max_loss=max_loss,
    )

    os.makedirs(tearsheet_dir, exist_ok=True)
    out_path = os.path.join(tearsheet_dir, f"H-004_{factor_col}.pdf")
    pdf = PdfPages(out_path)
    n_pages = 0
    _original_show = plt.show

    def _show_and_savefig(*args, **kwargs):
        nonlocal n_pages
        for num in list(plt.get_fignums()):
            fig = plt.figure(num)
            if fig.axes:
                pdf.savefig(fig, bbox_inches="tight")
                n_pages += 1
        plt.close("all")

    plt.show = _show_and_savefig
    try:
        al.tears.create_full_tear_sheet(factor_data, long_short=True)
        _show_and_savefig()
    finally:
        plt.show = _original_show
        pdf.close()
        plt.close("all")

    print(f"Wrote {out_path} ({n_pages} pages)")
    return factor_data

### 4.1 Window screen summary

Full IC / spread table sorted by `ic_5d`, plus a **best-by-family** table (one row per feature stem).

**Expected signs (literature / intuition):**
- `beta` / smart betas — context-dependent
- `downside_beta`, `rel_downside_beta` — often positive IC for high downside beta (Ang et al.)
- `residual_mom`, `smart_residual_mom` — positive IC for high residual momentum
- Compare each family's best window vs the `beta` baseline at a similar `W` where possible

In [6]:
t0 = time.perf_counter()
prices = to_alphalens_prices(panel)
rows = []
for col in FACTOR_COLS:
    meta = parse_beta_factor_name(col) or {}
    metrics = factor_screen_metrics(to_alphalens_factor(panel, col), prices)
    rows.append({"factor": col, **meta, **metrics})

summary = (
    pd.DataFrame(rows)
    .sort_values("ic_5d", ascending=False)
    .reset_index(drop=True)
)
print(f"Alphalens screen wall={time.perf_counter() - t0:.1f}s  n={len(summary)}")

summary["feature_family"] = summary["factor"].map(
    lambda c: (parse_beta_factor_name(c) or {}).get("feature")
)
best_by_family = (
    summary.sort_values("ic_5d", ascending=False)
    .groupby("feature_family", as_index=False)
    .first()
    .sort_values("ic_5d", ascending=False)
    .reset_index(drop=True)
)

print("\n=== Best by feature family (ic_5d) ===")
print(best_by_family.to_string())

print("\n=== Full screen (sorted by ic_5d) ===")

with pd.option_context("display.max_columns", None, "display.max_rows", None):
    display(summary)

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Alphalens screen wall=1065.3s  n=92

=== Best by feature family (ic_5d) ===
        feature_family                     factor             feature  window     ic_1d  spread_1d     ic_5d     spread_5d    ic_21d  spread_21d      K     S
0   smart_residual_mom  smart_residual_mom_189_42  smart_residual_mom     NaN  0.009161   0.000214  0.015781  1.057474e-03  0.036117    0.004279  189.0  42.0
1    rel_downside_beta      rel_downside_beta_252   rel_downside_beta   252.0  0.006535   0.000428  0.013537  1.851255e-03  0.032943    0.008049    NaN   NaN
2       smart_beta_mom         smart_beta_mom_126      smart_beta_mom   126.0  0.010606   0.000052  0.009720 -7.630758e-07 -0.005522   -0.002647    NaN   NaN
3       smart_beta_smb          smart_beta_smb_84      smart_beta_smb    84.0  0.001808   0.000417  0.009412  2.198209e-03  0.016292    0.007738    NaN   NaN
4      rel_upside_beta        rel_upside_beta_126     rel_upside_beta   126.0  0.007242   0.000174  0.009350  6.011669e-04  0.008629    0.001086    NaN   NaN
5      net_beta_spread         net_beta_spread_63     net_beta_spread    63.0  0.005852   0.000182  0.009275  3.179777e-04  0.009016   -0.000546    NaN   NaN
6        downside_beta          downside_beta_189       downside_beta   189.0 -0.000951   0.000367  0.008784  1.739122e-03  0.017653    0.007027    NaN   NaN
7         residual_mom        residual_mom_252_21        residual_mom     NaN  0.009661   0.000020  0.008760  3.545651e-04  0.008564    0.001372  252.0  21.0
8          upside_beta            upside_beta_126         upside_beta   126.0  0.001176   0.000243  0.008521  7.692803e-04  0.010686    0.002129    NaN   NaN
9           blume_beta             blume_beta_189          blume_beta   189.0 -0.003352   0.000256  0.005335  1.161722e-03  0.011238    0.004896    NaN   NaN
10                beta                   beta_189                beta   189.0 -0.003352   0.000256  0.005335  1.161722e-03  0.011238    0.004896    NaN   NaN
11      smart_beta_hml          smart_beta_hml_42      smart_beta_hml    42.0 -0.018379  -0.000454 -0.033915 -2.316379e-03 -0.046081   -0.006505    NaN   NaN

=== Full screen (sorted by ic_5d) ===

,factor,feature,window,ic_1d,spread_1d,ic_5d,spread_5d,ic_21d,spread_21d,K,S,feature_family
0,smart_residual_mom_189_42,smart_residual_mom,NaN,0.009161,2.140574e-04,0.015781,1.057474e-03,0.036117,0.004279,189.0,42.0,smart_residual_mom
1,smart_residual_mom_189_63,smart_residual_mom,NaN,0.009438,3.505460e-04,0.015555,1.875600e-03,0.029069,0.006454,189.0,63.0,smart_residual_mom
2,rel_downside_beta_252,rel_downside_beta,252.0,0.006535,4.282595e-04,0.013537,1.851255e-03,0.032943,0.008049,NaN,NaN,rel_downside_beta
3,smart_residual_mom_189_21,smart_residual_mom,NaN,0.008266,2.228039e-04,0.011449,1.426738e-03,0.033263,0.005292,189.0,21.0,smart_residual_mom
4,rel_downside_beta_189,rel_downside_beta,189.0,0.005069,2.728261e-04,0.010924,1.659669e-03,0.029477,0.007660,NaN,NaN,rel_downside_beta
5,smart_residual_mom_126_42,smart_residual_mom,NaN,0.006281,1.470190e-04,0.009834,1.144957e-03,0.025551,0.006346,126.0,42.0,smart_residual_mom
6,smart_beta_mom_126,smart_beta_mom,126.0,0.010606,5.232996e-05,0.009720,-7.630758e-07,-0.005522,-0.002647,NaN,NaN,smart_beta_mom
7,smart_beta_smb_84,smart_beta_smb,84.0,0.001808,4.167652e-04,0.009412,2.198209e-03,0.016292,0.007738,NaN,NaN,smart_beta_smb
8,rel_upside_beta_126,rel_upside_beta,126.0,0.007242,1.736734e-04,0.009350,6.011669e-04,0.008629,0.001086,NaN,NaN,rel_upside_beta
9,net_beta_spread_63,net_beta_spread,63.0,0.005852,1.818698e-04,0.009275,3.179777e-04,0.009016,-0.000546,NaN,NaN,net_beta_spread
10,downside_beta_189,downside_beta,189.0,-0.000951,3.672434e-04,0.008784,1.739122e-03,0.017653,0.007027,NaN,NaN,downside_beta
11,residual_mom_252_21,residual_mom,NaN,0.009661,1.963712e-05,0.008760,3.545651e-04,0.008564,0.001372,252.0,21.0,residual_mom
12,net_beta_spread_84,net_beta_spread,84.0,0.003942,3.306000e-06,0.008612,1.016071e-04,0.001727,-0.001974,NaN,NaN,net_beta_spread
13,smart_residual_mom_252_63,smart_residual_mom,NaN,0.009638,1.098540e-04,0.008562,6.739060e-04,0.007841,0.002499,252.0,63.0,smart_residual_mom
14,upside_beta_126,upside_beta,126.0,0.001176,2.433110e-04,0.008521,7.692803e-04,0.010686,0.002129,NaN,NaN,upside_beta
15,smart_residual_mom_189_10,smart_residual_mom,NaN,0.006333,1.089515e-04,0.008390,7.924613e-04,0.027496,0.004618,189.0,10.0,smart_residual_mom
16,upside_beta_42,upside_beta,42.0,0.003689,1.664535e-04,0.008281,5.067253e-04,0.007045,0.001882,NaN,NaN,upside_beta
17,rel_upside_beta_63,rel_upside_beta,63.0,0.007071,1.204666e-04,0.008279,3.343503e-04,0.003319,-0.000809,NaN,NaN,rel_upside_beta
18,upside_beta_189,upside_beta,189.0,0.000965,2.621129e-04,0.008066,1.220399e-03,0.014331,0.004789,NaN,NaN,upside_beta
19,residual_mom_252_42,residual_mom,NaN,0.008400,2.142425e-05,0.007990,1.324306e-04,0.006537,0.001468,252.0,42.0,residual_mom
20,smart_beta_mom_189,smart_beta_mom,189.0,0.009410,-1.403945e-04,0.007850,-9.369540e-04,-0.011948,-0.005238,NaN,NaN,smart_beta_mom
21,smart_beta_mom_42,smart_beta_mom,42.0,0.008112,2.082531e-05,0.007682,6.767521e-05,0.002268,0.000264,NaN,NaN,smart_beta_mom
22,residual_mom_84_42,residual_mom,NaN,0.004590,-6.432846e-05,0.007587,-3.165305e-04,0.000059,-0.001466,84.0,42.0,residual_mom
23,residual_mom_189_21,residual_mom,NaN,0.007224,1.755250e-04,0.007572,1.080053e-03,0.015177,0.003935,189.0,21.0,residual_mom
24,smart_beta_mom_63,smart_beta_mom,63.0,0.008860,1.045870e-04,0.007546,2.070475e-04,-0.006003,-0.000610,NaN,NaN,smart_beta_mom
25,smart_beta_smb_63,smart_beta_smb,63.0,0.002830,3.671254e-04,0.007510,1.838363e-03,0.016881,0.007333,NaN,NaN,smart_beta_smb
26,smart_beta_smb_42,smart_beta_smb,42.0,0.004147,3.144751e-04,0.007482,1.280121e-03,0.012189,0.005816,NaN,NaN,smart_beta_smb
27,smart_residual_mom_252_42,smart_residual_mom,NaN,0.008444,-2.929999e-05,0.007459,9.767382e-05,0.012329,0.001479,252.0,42.0,smart_residual_mom
28,smart_residual_mom_126_63,smart_residual_mom,NaN,0.005666,1.165923e-04,0.007448,7.902401e-04,0.020922,0.005793,126.0,63.0,smart_residual_mom
29,net_beta_spread_126,net_beta_spread,126.0,0.003800,6.857522e-05,0.007429,2.014292e-04,0.003460,0.000264,NaN,NaN,net_beta_spread
30,residual_mom_189_42,residual_mom,NaN,0.006017,1.591963e-04,0.007356,8.463243e-04,0.014733,0.003771,189.0,42.0,residual_mom
31,rel_upside_beta_189,rel_upside_beta,189.0,0.006410,2.844453e-05,0.007277,1.385024e-04,0.009276,-0.000303,NaN,NaN,rel_upside_beta
32,upside_beta_63,upside_beta,63.0,0.001841,1.958201e-04,0.006983,9.089335e-04,0.006051,0.002243,NaN,NaN,upside_beta
33,residual_mom_252_10,residual_mom,NaN,0.009105,4.813165e-05,0.006958,9.757297e-05,0.009293,0.001238,252.0,10.0,residual_mom
34,smart_beta_smb_126,smart_beta_smb,126.0,0.000737,4.038069e-04,0.006896,2.182185e-03,0.020526,0.009199,NaN,NaN,smart_beta_smb
35,smart_beta_mom_252,smart_beta_mom,252.0,0.007616,-1.009925e-04,0.006120,-6.892583e-04,-0.013273,-0.004831,NaN,NaN,smart_beta_mom
36,residual_mom_189_10,residual_mom,NaN,0.005960,1.220202e-04,0.006041,7.777055e-04,0.015292,0.004461,189.0,10.0,residual_mom
37,smart_beta_smb_252,smart_beta_smb,252.0,-0.000604,5.046359e-04,0.005485,2.695954e-03,0.020382,0.011075,NaN,NaN,smart_beta_smb
38,blume_beta_189,blume_beta,189.0,-0.003352,2.556125e-04,0.005335,1.161722e-03,0.011238,0.004896,NaN,NaN,blume_beta
39,beta_189,beta,189.0,-0.003352,2.556125e-04,0.005335,1.161722e-03,0.011238,0.004896,NaN,NaN,beta
40,residual_mom_189_63,residual_mom,NaN,0.004827,2.076632e-04,0.005289,9.432244e-04,0.009652,0.003659,189.0,63.0,residual_mom
41,residual_mom_84_63,residual_mom,NaN,0.004261,1.181244e-04,0.005046,5.210462e-04,-0.013578,-0.001115,84.0,63.0,residual_mom
42,residual_mom_84_21,residual_mom,NaN,0.003831,1.108648e-04,0.004899,4.879622e-04,0.002032,-0.000888,84.0,21.0,residual_mom
43,residual_mom_252_63,residual_mom,NaN,0.007483,3.413778e-05,0.004895,-9.563155e-05,0.001836,0.000157,252.0,63.0,residual_mom
44,upside_beta_252,upside_beta,252.0,-0.000729,2.160985e-04,0.004651,7.265781e-04,0.009999,0.002978,NaN,NaN,upside_beta
45,smart_residual_mom_84_42,smart_residual_mom,NaN,0.002821,-1.477672e-04,0.004237,-6.780064e-04,-0.004052,-0.002271,84.0,42.0,smart_residual_mom
46,rel_upside_beta_84,rel_upside_beta,84.0,0.003379,-1.246993e-04,0.004197,-5.158036e-04,-0.002103,-0.003283,NaN,NaN,rel_upside_beta
47,upside_beta_84,upside_beta,84.0,-0.001300,1.137947e-04,0.004152,4.064225e-04,0.002236,-0.000446,NaN,NaN,upside_beta
48,beta_126,beta,126.0,-0.003585,2.750013e-04,0.004104,1.240740e-03,0.007854,0.004155,NaN,NaN,beta
49,blume_beta_126,blume_beta,126.0,-0.003585,2.750013e-04,0.004104,1.240740e-03,0.007854,0.004155,NaN,NaN,blume_beta
50,smart_beta_mom_84,smart_beta_mom,84.0,0.008785,1.286754e-04,0.004075,3.120279e-04,-0.007588,0.000035,NaN,NaN,smart_beta_mom
51,smart_residual_mom_126_21,smart_residual_mom,NaN,0.004442,7.653670e-07,0.004019,2.618565e-04,0.022274,0.004213,126.0,21.0,smart_residual_mom
52,rel_upside_beta_252,rel_upside_beta,252.0,0.005707,-1.258821e-04,0.003859,-5.804932e-04,0.004049,-0.002452,NaN,NaN,rel_upside_beta
53,smart_beta_smb_189,smart_beta_smb,189.0,-0.000887,4.854322e-04,0.003698,2.331168e-03,0.016442,0.010085,NaN,NaN,smart_beta_smb
54,residual_mom_84_10,residual_mom,NaN,0.002213,5.130500e-05,0.003502,6.652248e-05,0.001612,-0.000681,84.0,10.0,residual_mom
55,downside_beta_252,downside_beta,252.0,-0.003451,2.716594e-04,0.003468,1.334882e-03,0.008454,0.005482,NaN,NaN,downside_beta
56,smart_residual_mom_252_21,smart_residual_mom,NaN,0.007981,-9.790108e-05,0.003369,-4.649125e-04,0.006780,0.000082,252.0,21.0,smart_residual_mom
57,smart_residual_mom_84_63,smart_residual_mom,NaN,0.003644,-5.202031e-05,0.002992,-4.512608e-04,-0.013431,-0.001636,84.0,63.0,smart_residual_mom
58,residual_mom_126_42,residual_mom,NaN,0.003333,6.697443e-05,0.002799,4.669982e-04,0.004142,0.003486,126.0,42.0,residual_mom
59,downside_beta_126,downside_beta,126.0,-0.003015,1.548563e-04,0.002212,7.807552e-04,0.008577,0.004255,NaN,NaN,downside_beta
60,blume_beta_84,blume_beta,84.0,-0.004989,1.611710e-04,0.001902,6.441065e-04,0.003424,0.002197,NaN,NaN,blume_beta
61,beta_84,beta,84.0,-0.004989,1.611710e-04,0.001902,6.441065e-04,0.003424,0.002197,NaN,NaN,beta
62,rel_upside_beta_42,rel_upside_beta,42.0,0.004799,-1.053486e-04,0.001812,-3.415282e-04,-0.000929,-0.001937,NaN,NaN,rel_upside_beta
63,smart_residual_mom_126_10,smart_residual_mom,NaN,0.002763,-2.629430e-05,0.001752,1.794420e-04,0.015930,0.003216,126.0,10.0,smart_residual_mom
64,beta_252,beta,252.0,-0.005085,2.364218e-04,0.001625,1.078679e-03,0.003056,0.003948,NaN,NaN,beta
65,blume_beta_252,blume_beta,252.0,-0.005085,2.364218e-04,0.001625,1.078679e-03,0.003056,0.003948,NaN,NaN,blume_beta
66,smart_residual_mom_84_21,smart_residual_mom,NaN,0.001990,9.577419e-06,0.001077,-2.424516e-04,-0.002035,-0.001785,84.0,21.0,smart_residual_mom
67,blume_beta_42,blume_beta,42.0,-0.005010,2.032837e-04,0.000937,8.213281e-04,-0.002484,0.001889,NaN,NaN,blume_beta
68,beta_42,beta,42.0,-0.005010,2.032837e-04,0.000937,8.213281e-04,-0.002484,0.001889,NaN,NaN,beta
69,blume_beta_63,blume_beta,63.0,-0.005756,1.187925e-04,0.000925,5.279058e-04,-0.001362,0.001501,NaN,NaN,blume_beta
70,beta_63,beta,63.0,-0.005756,1.187925e-04,0.000925,5.279058e-04,-0.001362,0.001501,NaN,NaN,beta
71,smart_residual_mom_252_10,smart_residual_mom,NaN,0.007535,-3.555833e-05,0.000645,-3.749924e-04,0.001804,-0.000738,252.0,10.0,smart_residual_mom
72,residual_mom_126_21,residual_mom,NaN,0.002492,4.015241e-06,0.000475,2.309828e-04,0.006391,0.002530,126.0,21.0,residual_mom
73,smart_residual_mom_84_10,smart_residual_mom,NaN,0.000199,-1.958119e-04,-0.000105,-7.289767e-04,-0.003686,-0.002566,84.0,10.0,smart_residual_mom
74,net_beta_spread_42,net_beta_spread,42.0,-0.000306,-1.610354e-04,-0.001253,-8.866764e-04,0.016358,-0.000108,NaN,NaN,net_beta_spread
75,residual_mom_126_63,residual_mom,NaN,0.000951,6.140978e-05,-0.001785,1.853539e-04,-0.004103,0.001804,126.0,63.0,residual_mom
76,residual_mom_126_10,residual_mom,NaN,0.000874,-1.045822e-05,-0.002259,1.619749e-04,0.003856,0.002450,126.0,10.0,residual_mom
77,downside_beta_63,downside_beta,63.0,-0.005541,-4.912732e-06,-0.002604,2.389486e-04,-0.007213,0.001120,NaN,NaN,downside_beta
78,net_beta_spread_189,net_beta_spread,189.0,0.001144,-1.115028e-04,-0.002663,-6.977145e-04,-0.011757,-0.004797,NaN,NaN,net_beta_spread
79,rel_downside_beta_126,rel_downside_beta,126.0,0.000869,-3.920288e-05,-0.002697,5.217188e-05,0.004145,0.001234,NaN,NaN,rel_downside_beta
80,downside_beta_42,downside_beta,42.0,-0.009006,1.276997e-06,-0.002870,8.416096e-04,-0.017207,-0.000133,NaN,NaN,downside_beta
81,downside_beta_84,downside_beta,84.0,-0.006385,2.516159e-05,-0.004514,2.802571e-04,-0.002994,0.001619,NaN,NaN,downside_beta
82,net_beta_spread_252,net_beta_spread,252.0,-0.000151,-1.997400e-04,-0.005828,-1.060770e-03,-0.017436,-0.005058,NaN,NaN,net_beta_spread
83,rel_downside_beta_63,rel_downside_beta,63.0,-0.001579,-1.794930e-04,-0.006396,-4.027292e-04,-0.007509,-0.000008,NaN,NaN,rel_downside_beta
84,rel_downside_beta_84,rel_downside_beta,84.0,-0.002419,-4.042499e-05,-0.007207,-1.719683e-04,-0.003007,0.000575,NaN,NaN,rel_downside_beta
85,rel_downside_beta_42,rel_downside_beta,42.0,-0.002842,-1.231937e-04,-0.007665,-1.707339e-04,-0.015058,-0.001889,NaN,NaN,rel_downside_beta
86,smart_beta_hml_42,smart_beta_hml,42.0,-0.018379,-4.541629e-04,-0.033915,-2.316379e-03,-0.046081,-0.006505,NaN,NaN,smart_beta_hml
87,smart_beta_hml_63,smart_beta_hml,63.0,-0.019097,-4.979450e-04,-0.037913,-2.716147e-03,-0.062660,-0.009707,NaN,NaN,smart_beta_hml
88,smart_beta_hml_126,smart_beta_hml,126.0,-0.020764,-5.915701e-04,-0.039866,-2.938318e-03,-0.064480,-0.012140,NaN,NaN,smart_beta_hml
89,smart_beta_hml_84,smart_beta_hml,84.0,-0.020976,-5.944679e-04,-0.040935,-2.892945e-03,-0.067188,-0.010954,NaN,NaN,smart_beta_hml
90,smart_beta_hml_189,smart_beta_hml,189.0,-0.022893,-7.327174e-04,-0.043919,-3.583359e-03,-0.071403,-0.013398,NaN,NaN,smart_beta_hml
91,smart_beta_hml_252,smart_beta_hml,252.0,-0.024773,-7.340958e-04,-0.048590,-3.611237e-03,-0.078901,-0.014093,NaN,NaN,smart_beta_hml

### 4.2 Full tear sheets

Edit `TEAR_FACTORS` after reviewing §4.1. Each tear is displayed in-notebook **and** saved as a multi-page PDF under:

`02_research/notebooks/s1_equities/factor_tests/tearsheets/H-004_{factor_col}.pdf`

Filename encodes the factor stem and window arguments (e.g. `H-004_residual_mom_126_21.pdf`). Re-running overwrites the same paths. **Do not** tear all 92 columns (runtime budget).

In [8]:
# Edit after reviewing §4.1 (defaults are placeholders from the plan)
TEAR_FACTORS = [
    "smart_residual_mom_189_42",
    "rel_downside_beta_252",
    "smart_beta_mom_126",
    "smart_beta_smb_84",
    "rel_upside_beta_126",
    "net_beta_spread_63",
    "downside_beta_189",
    "residual_mom_252_21",
    "upside_beta_126",
    "blume_beta_189",
    "beta_189",
    "smart_beta_hml_252",
    "smart_beta_hml_42"
]

for tear_col in TEAR_FACTORS:
    print(f"\n===== Tear sheet: {tear_col} =====")
    run_full_tear(panel, tear_col, prices)

===== Tear sheet: smart_residual_mom_189_42 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1               -0.280489 -0.031971 -0.100088  0.032852  33780  20.245851
2               -0.095874  0.014460 -0.041192  0.016424  33130  19.856277
3               -0.045074  0.051938 -0.002045  0.015006  33030  19.796343
4               -0.010923  0.093036  0.036071  0.016809  33130  19.856277
5                0.022746  0.335100  0.098595  0.038080  33779  20.245252

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                     0.037  0.047  0.048
beta                                          -0.031 -0.057 -0.074
Mean Period Wise Return Top Quantile (bps)     0.769  0.875  0.911
Mean Period Wise Return Bottom Quantile (bps) -1.372 -1.240 -1.127
Mean Period Wise Spread (bps)                  2.141  2.114  2.033

Information Analysis

                     1D     5D    21D
IC Mean           0.009  0.016  0.036
IC Std.           0.177  0.177  0.185
Risk-Adjusted IC  0.052  0.089  0.196
t-stat(IC)        2.127  3.673  8.035
p-value(IC)       0.034  0.000  0.000
IC Skew          -0.015 -0.111 -0.042
IC Kurtosis      -0.137 -0.102 -0.100

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.075  0.164  0.348
Quantile 2 Mean Turnover   0.176  0.368  0.626
Quantile 3 Mean Turnover   0.204  0.421  0.663
Quantile 4 Mean Turnover   0.182  0.377  0.621
Quantile 5 Mean Turnover   0.077  0.168  0.353

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.988  0.946  0.789

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_smart_residual_mom_189_42.pdf (3 pages)

===== Tear sheet: rel_downside_beta_252 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.206186  0.105839  0.058146  52820  20.156536
2                0.210000  0.404040  0.306131  0.057435  52170  19.908490
3                0.408163  0.602041  0.505039  0.057299  52070  19.870330
4                0.606061  0.804124  0.703949  0.057431  52170  19.908490
5                0.804124  1.000000  0.904243  0.058141  52819  20.156154

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                     0.029  0.028  0.031
beta                                           0.057  0.061  0.046
Mean Period Wise Return Top Quantile (bps)     2.245  2.136  1.969
Mean Period Wise Return Bottom Quantile (bps) -2.038 -1.566 -1.864
Mean Period Wise Spread (bps)                  4.283  3.657  3.767

Information Analysis

                     1D     5D    21D
IC Mean           0.007  0.014  0.033
IC Std.           0.182  0.184  0.172
Risk-Adjusted IC  0.036  0.074  0.191
t-stat(IC)        1.844  3.787  9.824
p-value(IC)       0.065  0.000  0.000
IC Skew          -0.020 -0.072 -0.098
IC Kurtosis      -0.208 -0.225 -0.250

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.055  0.115  0.231
Quantile 2 Mean Turnover   0.132  0.265  0.472
Quantile 3 Mean Turnover   0.150  0.297  0.508
Quantile 4 Mean Turnover   0.126  0.253  0.443
Quantile 5 Mean Turnover   0.053  0.112  0.219

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.989  0.962  0.876

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_rel_downside_beta_252.pdf (3 pages)

===== Tear sheet: smart_beta_mom_126 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.216495  0.106147  0.058317  38800  20.213703
2                0.210000  0.412371  0.306552  0.057346  38150  19.875071
3                0.408163  0.608247  0.505058  0.057164  38050  19.822974
4                0.606061  0.804124  0.703563  0.057341  38150  19.875071
5                0.804124  1.000000  0.903969  0.058311  38799  20.213182

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                     0.031  0.030  0.033
beta                                          -0.161 -0.198 -0.279
Mean Period Wise Return Top Quantile (bps)     1.089  0.631 -0.185
Mean Period Wise Return Bottom Quantile (bps)  0.566  0.632  1.074
Mean Period Wise Spread (bps)                  0.523  0.120 -1.071

Information Analysis

                     1D     5D    21D
IC Mean           0.011  0.010 -0.006
IC Std.           0.247  0.239  0.245
Risk-Adjusted IC  0.043  0.041 -0.023
t-stat(IC)        1.892  1.791 -0.993
p-value(IC)       0.059  0.073  0.321
IC Skew          -0.047 -0.117  0.053
IC Kurtosis      -0.348 -0.159 -0.278

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.040  0.099  0.215
Quantile 2 Mean Turnover   0.095  0.228  0.443
Quantile 3 Mean Turnover   0.106  0.251  0.481
Quantile 4 Mean Turnover   0.086  0.210  0.421
Quantile 5 Mean Turnover   0.036  0.087  0.190

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.995  0.975  0.899

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_smart_beta_mom_126.pdf (3 pages)

===== Tear sheet: smart_beta_smb_84 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.206186  0.106118  0.058302  39640  20.209127
2                0.210000  0.404040  0.306514  0.057352  38990  19.877746
3                0.408163  0.602041  0.505052  0.057175  38890  19.826764
4                0.606061  0.800000  0.703589  0.057348  38990  19.877746
5                0.804124  1.000000  0.903986  0.058298  39639  20.208617

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                    -0.005 -0.012 -0.012
beta                                           0.253  0.303  0.289
Mean Period Wise Return Top Quantile (bps)     1.442  2.031  1.814
Mean Period Wise Return Bottom Quantile (bps) -2.725 -2.366 -1.871
Mean Period Wise Spread (bps)                  4.168  4.267  3.565

Information Analysis

                     1D     5D    21D
IC Mean           0.002  0.009  0.016
IC Std.           0.231  0.224  0.210
Risk-Adjusted IC  0.008  0.042  0.078
t-stat(IC)        0.349  1.869  3.453
p-value(IC)       0.727  0.062  0.001
IC Skew          -0.032  0.036  0.092
IC Kurtosis      -0.287 -0.110 -0.309

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.061  0.147  0.317
Quantile 2 Mean Turnover   0.143  0.328  0.559
Quantile 3 Mean Turnover   0.157  0.358  0.602
Quantile 4 Mean Turnover   0.130  0.304  0.548
Quantile 5 Mean Turnover   0.056  0.138  0.296

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.989  0.949  0.806

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_smart_beta_smb_84.pdf (3 pages)

===== Tear sheet: rel_upside_beta_126 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.216495  0.105804  0.058125  55340  20.149354
2                0.210000  0.412371  0.306083  0.057446  54690  19.912689
3                0.408163  0.608247  0.505040  0.057316  54590  19.876278
4                0.606061  0.804124  0.703998  0.057442  54690  19.912689
5                0.804124  1.000000  0.904277  0.058120  55339  20.148990

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                     0.037  0.034  0.012
beta                                          -0.114 -0.118 -0.031
Mean Period Wise Return Top Quantile (bps)     0.892  1.037  0.928
Mean Period Wise Return Bottom Quantile (bps) -0.845 -0.165  0.412
Mean Period Wise Spread (bps)                  1.737  1.255  0.565

Information Analysis

                     1D     5D    21D
IC Mean           0.007  0.009  0.009
IC Std.           0.166  0.161  0.161
Risk-Adjusted IC  0.044  0.058  0.054
t-stat(IC)        2.301  3.051  2.820
p-value(IC)       0.021  0.002  0.005
IC Skew           0.006 -0.136  0.126
IC Kurtosis       0.679  1.019  0.994

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.085  0.177  0.333
Quantile 2 Mean Turnover   0.195  0.373  0.580
Quantile 3 Mean Turnover   0.232  0.428  0.631
Quantile 4 Mean Turnover   0.207  0.391  0.598
Quantile 5 Mean Turnover   0.090  0.188  0.364

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.974  0.916  0.746

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_rel_upside_beta_126.pdf (3 pages)

===== Tear sheet: net_beta_spread_63 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.206186  0.105778  0.058111  56480  20.144952
2                0.210000  0.404040  0.306048  0.057453  55836  19.915254
3                0.408163  0.602041  0.505036  0.057325  55736  19.879587
4                0.606061  0.800000  0.704023  0.057449  55836  19.915254
5                0.804124  1.000000  0.904296  0.058108  56480  20.144952

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                     0.034  0.024  0.009
beta                                          -0.053 -0.059 -0.043
Mean Period Wise Return Top Quantile (bps)     1.288  0.880  0.382
Mean Period Wise Return Bottom Quantile (bps) -0.531  0.245  0.642
Mean Period Wise Spread (bps)                  1.819  0.678 -0.230

Information Analysis

                     1D     5D    21D
IC Mean           0.006  0.009  0.009
IC Std.           0.169  0.168  0.171
Risk-Adjusted IC  0.035  0.055  0.053
t-stat(IC)          NaN    NaN    NaN
p-value(IC)         NaN    NaN    NaN
IC Skew             NaN    NaN    NaN
IC Kurtosis         NaN    NaN    NaN

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.099  0.229  0.464
Quantile 2 Mean Turnover   0.223  0.453  0.678
Quantile 3 Mean Turnover   0.257  0.505  0.706
Quantile 4 Mean Turnover   0.229  0.462  0.685
Quantile 5 Mean Turnover   0.102  0.237  0.479

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.969  0.874  0.574

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_net_beta_spread_63.pdf (3 pages)

===== Tear sheet: downside_beta_189 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.206186  0.105820  0.058134  54080  20.152861
2                0.210000  0.404040  0.306105  0.057440  53430  19.910639
3                0.408163  0.602041  0.505038  0.057307  53330  19.873374
4                0.606061  0.800000  0.703971  0.057436  53430  19.910639
5                0.804124  1.000000  0.904260  0.058131  54079  20.152488

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                    -0.030 -0.034 -0.035
beta                                           0.343  0.380  0.386
Mean Period Wise Return Top Quantile (bps)     2.099  2.072  2.033
Mean Period Wise Return Bottom Quantile (bps) -1.573 -1.406 -1.310
Mean Period Wise Spread (bps)                  3.672  3.356  3.186

Information Analysis

                     1D     5D    21D
IC Mean          -0.001  0.009  0.018
IC Std.           0.279  0.277  0.274
Risk-Adjusted IC -0.003  0.032  0.064
t-stat(IC)       -0.177  1.652  3.352
p-value(IC)       0.859  0.099  0.001
IC Skew          -0.065 -0.079 -0.055
IC Kurtosis      -0.335 -0.405 -0.476

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.030  0.071  0.151
Quantile 2 Mean Turnover   0.072  0.167  0.324
Quantile 3 Mean Turnover   0.085  0.195  0.360
Quantile 4 Mean Turnover   0.076  0.175  0.331
Quantile 5 Mean Turnover   0.032  0.076  0.153

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.995  0.983  0.938

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_downside_beta_189.pdf (3 pages)

===== Tear sheet: residual_mom_252_21 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1               -0.217470 -0.019237 -0.074711  0.024047  47800  20.173117
2               -0.076063  0.012500 -0.031253  0.011911  47150  19.898797
3               -0.041737  0.054870 -0.001944  0.012000  47050  19.856594
4               -0.009374  0.093580  0.027058  0.014492  47150  19.898797
5                0.017122  0.207581  0.072551  0.026969  47799  20.172695

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                     0.019  0.023  0.022
beta                                          -0.041 -0.073 -0.086
Mean Period Wise Return Top Quantile (bps)     0.273  0.542  0.282
Mean Period Wise Return Bottom Quantile (bps)  0.077 -0.167 -0.372
Mean Period Wise Spread (bps)                  0.196  0.722  0.676

Information Analysis

                     1D     5D    21D
IC Mean           0.010  0.009  0.009
IC Std.           0.211  0.207  0.205
Risk-Adjusted IC  0.046  0.042  0.042
t-stat(IC)        2.235  2.071  2.040
p-value(IC)       0.025  0.038  0.041
IC Skew          -0.097 -0.088 -0.138
IC Kurtosis      -0.031 -0.127  0.005

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.066  0.145  0.303
Quantile 2 Mean Turnover   0.152  0.327  0.574
Quantile 3 Mean Turnover   0.169  0.360  0.615
Quantile 4 Mean Turnover   0.149  0.318  0.568
Quantile 5 Mean Turnover   0.064  0.141  0.295

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.991  0.962  0.847

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_residual_mom_252_21.pdf (3 pages)

===== Tear sheet: upside_beta_126 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.216495  0.105804  0.058125  55340  20.149354
2                0.210000  0.412371  0.306083  0.057446  54690  19.912689
3                0.408163  0.608247  0.505040  0.057316  54590  19.876278
4                0.606061  0.804124  0.703998  0.057442  54690  19.912689
5                0.804124  1.000000  0.904277  0.058120  55339  20.148990

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                    -0.014 -0.020 -0.034
beta                                           0.215  0.232  0.287
Mean Period Wise Return Top Quantile (bps)     0.974  0.656  0.662
Mean Period Wise Return Bottom Quantile (bps) -1.459 -0.883 -0.351
Mean Period Wise Spread (bps)                  2.433  1.473  0.938

Information Analysis

                     1D     5D    21D
IC Mean           0.001  0.009  0.011
IC Std.           0.250  0.251  0.253
Risk-Adjusted IC  0.005  0.034  0.042
t-stat(IC)        0.247  1.788  2.226
p-value(IC)       0.805  0.074  0.026
IC Skew          -0.040 -0.102 -0.059
IC Kurtosis      -0.201 -0.233 -0.251

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.057  0.127  0.253
Quantile 2 Mean Turnover   0.129  0.275  0.477
Quantile 3 Mean Turnover   0.145  0.304  0.513
Quantile 4 Mean Turnover   0.128  0.270  0.469
Quantile 5 Mean Turnover   0.057  0.125  0.242

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.987  0.956  0.863

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_upside_beta_126.pdf (3 pages)

===== Tear sheet: blume_beta_189 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.094371  0.916744  0.734049  0.102188  54080  20.152861
2                0.719093  1.060058  0.911083  0.051645  53430  19.910639
3                0.875221  1.172563  1.030530  0.046622  53330  19.873374
4                0.977413  1.420166  1.159793  0.062863  53430  19.910639
5                1.103271  2.616508  1.414330  0.192667  54079  20.152488

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                    -0.040 -0.048 -0.048
beta                                           0.424  0.484  0.500
Mean Period Wise Return Top Quantile (bps)     1.464  1.452  1.373
Mean Period Wise Return Bottom Quantile (bps) -1.092 -0.871 -0.957
Mean Period Wise Spread (bps)                  2.556  2.199  2.185

Information Analysis

                     1D     5D    21D
IC Mean          -0.003  0.005  0.011
IC Std.           0.309  0.308  0.306
Risk-Adjusted IC -0.011  0.017  0.037
t-stat(IC)       -0.564  0.900  1.908
p-value(IC)       0.573  0.368  0.056
IC Skew          -0.070 -0.068 -0.035
IC Kurtosis      -0.507 -0.563 -0.669

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.018  0.044  0.094
Quantile 2 Mean Turnover   0.041  0.103  0.221
Quantile 3 Mean Turnover   0.048  0.119  0.260
Quantile 4 Mean Turnover   0.042  0.105  0.234
Quantile 5 Mean Turnover   0.018  0.045  0.102

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.999  0.994  0.975

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_blume_beta_189.pdf (3 pages)

===== Tear sheet: beta_189 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.206186  0.105820  0.058134  54080  20.152861
2                0.210000  0.404040  0.306105  0.057440  53430  19.910639
3                0.408163  0.602041  0.505038  0.057307  53330  19.873374
4                0.606061  0.804124  0.703971  0.057437  53430  19.910639
5                0.804124  1.000000  0.904260  0.058130  54079  20.152488

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                    -0.038 -0.044 -0.045
beta                                           0.371  0.413  0.425
Mean Period Wise Return Top Quantile (bps)     1.464  1.452  1.373
Mean Period Wise Return Bottom Quantile (bps) -1.092 -0.871 -0.957
Mean Period Wise Spread (bps)                  2.556  2.199  2.185

Information Analysis

                     1D     5D    21D
IC Mean          -0.003  0.005  0.011
IC Std.           0.309  0.308  0.306
Risk-Adjusted IC -0.011  0.017  0.037
t-stat(IC)       -0.564  0.900  1.908
p-value(IC)       0.573  0.368  0.056
IC Skew          -0.070 -0.068 -0.035
IC Kurtosis      -0.507 -0.563 -0.669

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.018  0.044  0.094
Quantile 2 Mean Turnover   0.041  0.103  0.221
Quantile 3 Mean Turnover   0.048  0.119  0.260
Quantile 4 Mean Turnover   0.042  0.105  0.234
Quantile 5 Mean Turnover   0.018  0.045  0.102

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.999  0.994  0.975

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_beta_189.pdf (3 pages)

===== Tear sheet: smart_beta_hml_252 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.206186  0.106222  0.058360  36280  20.228716
2                0.210000  0.404040  0.306657  0.057321  35630  19.866294
3                0.408163  0.602041  0.505056  0.057128  35530  19.810537
4                0.606061  0.804124  0.703460  0.057318  35630  19.866294
5                0.804124  1.000000  0.903897  0.058355  36279  20.228159

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                    -0.078 -0.085 -0.086
beta                                           0.090  0.134  0.156
Mean Period Wise Return Top Quantile (bps)    -2.255 -2.288 -1.981
Mean Period Wise Return Bottom Quantile (bps)  5.086  4.931  4.711
Mean Period Wise Spread (bps)                 -7.341 -7.328 -6.856

Information Analysis

                     1D     5D     21D
IC Mean          -0.025 -0.049  -0.079
IC Std.           0.253  0.243   0.232
Risk-Adjusted IC -0.098 -0.200  -0.340
t-stat(IC)       -4.176 -8.532 -14.480
p-value(IC)       0.000  0.000   0.000
IC Skew           0.061  0.238   0.274
IC Kurtosis      -0.499 -0.547  -0.295

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.017  0.042  0.089
Quantile 2 Mean Turnover   0.045  0.109  0.229
Quantile 3 Mean Turnover   0.056  0.137  0.286
Quantile 4 Mean Turnover   0.050  0.120  0.254
Quantile 5 Mean Turnover   0.021  0.050  0.111

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.998  0.992  0.971

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_smart_beta_hml_252.pdf (3 pages)

===== Tear sheet: smart_beta_hml_42 =====

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:308: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change(period)

Quantiles Statistics

                      min       max      mean       std  count    count %
factor_quantile
1                0.010000  0.206186  0.106095  0.058289  40480  20.204743
2                0.210000  0.404040  0.306482  0.057359  39830  19.880309
3                0.408163  0.608247  0.505054  0.057187  39730  19.830396
4                0.606061  0.804124  0.703624  0.057355  39830  19.880309
5                0.804124  1.000000  0.904012  0.058285  40479  20.204244

Returns Analysis

                                                  1D     5D    21D
Ann. alpha                                    -0.054 -0.059 -0.049
beta                                           0.072  0.104  0.133
Mean Period Wise Return Top Quantile (bps)    -1.395 -1.269 -0.303
Mean Period Wise Return Bottom Quantile (bps)  3.147  3.362  2.787
Mean Period Wise Spread (bps)                 -4.542 -4.741 -3.228

Information Analysis

                     1D     5D     21D
IC Mean          -0.018 -0.034  -0.046
IC Std.           0.225  0.216   0.195
Risk-Adjusted IC -0.082 -0.157  -0.236
t-stat(IC)       -3.681 -7.060 -10.624
p-value(IC)       0.000  0.000   0.000
IC Skew           0.087  0.134   0.367
IC Kurtosis      -0.099 -0.173   0.628

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\performance.py:118: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  grouper.append(pd.Grouper(freq=by_time))
c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\alphalens\utils.py:928: UserWarning: Skipping return periods that aren't exact multiples of days.
  warnings.warn(

Turnover Analysis

                              1D     5D    21D
Quantile 1 Mean Turnover   0.072  0.181  0.395
Quantile 2 Mean Turnover   0.176  0.399  0.649
Quantile 3 Mean Turnover   0.215  0.454  0.683
Quantile 4 Mean Turnover   0.191  0.415  0.651
Quantile 5 Mean Turnover   0.081  0.201  0.418

                                     1D     5D    21D
Mean Factor Rank Autocorrelation  0.979  0.906  0.666

Wrote c:\Users\User\Desktop\ML Algorithmic Trading\Portfolio 26\trading_portfolio\02_research\notebooks\factor_tests\tearsheets\H-004_smart_beta_hml_42.pdf (3 pages)

## 5. Conclusion

- **Variants tried:** `EXPECTED_N_FACTORS` (= 92 with the locked balanced grid) H-004 factor columns on research IS only.
- **Primary metric:** `ic_5d` (also report 1d / 21d). Use §4.1 `best_by_family` to shortlist 1–2 combos per surviving family for a later `feature_spec` freeze — do **not** integrate into `s1_factor_panel.ipynb` yet.
- **Cache:** this run was a CACHE HIT or COLD build depending on §1; invalidate `s1_h004_beta_panel.parquet` (or set `FORCE_REBUILD = True`) when changing windows, store code, **or the factor backend** (Ken French ZIP → ETF Tier A).
- **Factor source:** ETF proxies via `data.ingestion.alternative_data.fama_french_fetcher` (archived Ken French path under `02_research/notebooks/s1_equities/redundant/`).
- **Holdout:** reserved; do not peek at `s1_factor_panel_full.parquet` for keep/kill.
- **Tear PDFs:** three files under `02_research/notebooks/s1_equities/factor_tests/tearsheets/` named `H-004_{factor_col}.pdf`.
- If cold-run wall time exceeded ~20 minutes, OLS dominated — trim `WINDOWS` in §0 and rebuild.